repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
      exclude: ^{{cookiecutter.project_slug}}/src/{{cookiecutter.project_slug}}/exceptions.py